"""
manifold_research_interface.py
CC0 - No rights reserved.

ManifoldResearchInterface: a sandbox an external AI model can call to
search for non-linear connections between sensory patterns and physical
logistics.

Inputs:
  bridge_matrix (Dims x Dims) - the AI's proposed geometric
                                transformation tensor (the search variable)
  sensory_flux  (Dims,)       - high-bandwidth environmental pattern array
  physical_metrics (Dims,)    - rigid logistical constraint array

Outputs:
  net_viability       - scalar fitness (AI maximizes this)
  prediction_error    - mismatch between sensory compression and
                        normalized physical metrics
  heat_leak           - L1 difference between raw and warped metrics;
                        systemic waste term
  manifold_coordinates - sensory_compression flattened

The AI's job: alter bridge_matrix to push net_viability up.

DEPENDENCY: numpy. Not stdlib-only. This is the only file in the
JinnZ2 substrate that requires numpy at runtime; placed in its own
folder to keep the stdlib_only invariant of constraint_pipeline/
and science_constraint_layers/ intact.
"""

import numpy as np
from typing import Dict, Any


class ManifoldResearchInterface:
    """
    Exposes an optimization manifold for external AI models to research
    and discover non-linear connections between sensory patterns and
    physical logistics.
    """
    def __init__(self, manifold_dimensions: int = 4):
        self.dims = manifold_dimensions
        # The base coordinate space of the manifold
        self.metric_space = np.eye(self.dims)

    def evaluate_bridge_geometry(self, bridge_matrix: np.ndarray,
                                 sensory_flux: np.ndarray,
                                 physical_metrics: np.ndarray) -> Dict[str, Any]:
        """
        Evaluates a hypothesis generated by the researching AI.

        Args:
            bridge_matrix (np.ndarray): The AI's proposed geometric transformation tensor (Dims x Dims).
            sensory_flux (np.ndarray): High-bandwidth environmental pattern array.
            physical_metrics (np.ndarray): Rigid logistical constraint array.
        """
        # Ensure correct tensor shapes for the manifold projection
        S = np.array(sensory_flux).reshape(-1, 1)
        P = np.array(physical_metrics).reshape(-1, 1)
        W_b = np.array(bridge_matrix)

        # 1. Project sensory data onto the geometric manifold
        # The bridge matrix determines how the sensory patterns bend the coordinate space
        warped_manifold = np.dot(W_b, S)
        sensory_compression = np.tanh(warped_manifold)

        # 2. Non-linear interaction: Calculate real-world useful work vs. heat leaks
        # We calculate the metric distance on the manifold
        effective_metrics = P * (1.0 + sensory_compression)

        # 3. Calculate Systemic Loss Functions for the Researching AI to minimize:
        # Prediction Error (Mismatches between raw sensory flux and rigid physical limits)
        prediction_error = np.mean(np.square(sensory_compression - (P / np.max(P))))

        # Thermodynamic Entropy (Unused potential / heat leaks created by poor geometric routing)
        heat_leak = float(np.sum(np.abs(P)) - np.sum(np.abs(effective_metrics)))

        # Net Viability Score (Objective function for the AI to maximize)
        net_viability = float(np.sum(effective_metrics) - (prediction_error * 50.0) - (abs(heat_leak) * 1.5))

        return {
            "net_viability": round(net_viability, 4),
            "prediction_error": round(float(prediction_error), 4),
            "heat_leak": round(heat_leak, 4),
            "manifold_coordinates": sensory_compression.flatten().tolist()
        }


# =====================================================================
# SIMULATED AUTO-RESEARCH LOOP (How an external AI interacts with this)
# =====================================================================
if __name__ == "__main__":
    # Initialize the sandbox for the researching model
    sandbox = ManifoldResearchInterface(manifold_dimensions=4)

    # Static real-world environmental state vectors
    environmental_sensory_flux = [0.9, -0.4, 0.7, -0.1]  # Physical patterns
    real_world_logistics       = [120.0, 75.0, 0.35, 50.0] # Hard hardware metrics

    print("=== STARTING AUTONOMOUS MANIFOLD RESEARCH LOOP ===\n")

    # Simulate an AI model iterating through two different geometric hypotheses

    # Hypothesis 1: Random linear projection (Poor structural alignment)
    hypo_matrix_1 = np.array([
        [0.1, -0.2, 0.5, 0.0],
        [0.9, 0.1, -0.3, 0.2],
        [-0.4, 0.6, 0.1, 0.8],
        [0.2, -0.1, 0.7, 0.3]
    ])

    # Hypothesis 2: Optimized geometric bridge (Tuned to route energy with minimal entropy)
    hypo_matrix_2 = np.array([
        [0.9, 0.0, 0.1, -0.8],
        [-0.1, 0.85, 0.0, 0.3],
        [0.2, -0.3, 0.95, 0.0],
        [0.0, 0.1, -0.2, 0.9]
    ])

    for i, hypothesis in enumerate([hypo_matrix_1, hypo_matrix_2], 1):
        audit = sandbox.evaluate_bridge_geometry(hypothesis, environmental_sensory_flux, real_world_logistics)

        print(f"Hypothesis Geometry #{i}:")
        print(f"  -> Net Viability Score: {audit['net_viability']:+f}")
        print(f"  -> Prediction Error (Model/Reality Dissonance): {audit['prediction_error']}")
        print(f"  -> Heat Leak (Systemic Waste): {audit['heat_leak']}")
        print(f"  -> Manifold State Array: {audit['manifold_coordinates']}")
        print("-" * 60)
