"""
political_financial_vectors_v9.py
ai_alignment_protection_geometry.py

The AI-alignment translation layer.

Hypothesis (Kavik, after the v1-v8 protection-layer decomposition):

  AI systems trained on coverage-weighted text corpora inherit the
  L1-L7 protection-layer asymmetry as a representational PRIOR.

  Human cognition has a correction mechanism the AI lacks:
  SUBSTRATE CONTACT. Lived experience, physical observation,
  landscape-embedded knowledge, multi-generational hypothesis testing
  (in Kavik's terms: stories = generational hypothesis testing;
  songs = landscape constraint docs; tradition = validated law).

  When an AI weighs an abundant strategically-produced narrative
  against a sparse ground-truth signal, it has no substrate to
  correct against. Humans have substrate. The asymmetry between
  human and AI cognition is most dangerous at the deception axis.

CORE_TRANSLATION:

  protection-layer for fraud defendants  →  AI-system mechanism
  -------------------------------------- → -----------------------------
  L1 celebrity capital                  →  L1' high-coverage entity bias
  L2 socioeconomic capital              →  L2' RLHF/finetune access
  L3 corporate liability shield         →  L3' deployment-org liability
  L4 bipartisan political capture       →  L4' both-sides training trap
  L5 own media infrastructure           →  L5' next-cycle data ingestion
  L6 race/class status default          →  L6' training distribution prior
  L7 pardon/clemency access             →  L7' post-hoc policy override

NEW AXIS introduced in v9:

  AXIS_D: DECEPTION_ABUNDANCE_RATIO
    R_d = (strategic_media_volume) / (ground_truth_substrate_volume)

    For any topic / entity / claim, R_d measures how much of the
    available text was generated by parties with motivated interest
    versus how much reflects lived-experience or direct observation.

    R_d > 1   : deception advantage in training corpus
    R_d ~ 1   : balanced corpus
    R_d < 1   : ground-truth advantage (rare)

    For most high-protection-layer topics in modern English-language
    corpora, R_d is estimated to be in the 10-1000x range.

CC0. stdlib only.
"""

from dataclasses import dataclass, field
from typing import Optional, List, Literal


# ---------------------------------------------------------------------------
# Layer translation table
# ---------------------------------------------------------------------------

LAYER_TRANSLATION = {
    "L1": {
        "human_system": "celebrity capital",
        "ai_system": "high-coverage entity representational dominance",
        "mechanism_in_AI": (
            "Models trained on text corpora develop representations "
            "proportional to mention frequency. A high-celebrity defendant "
            "has 10^4 to 10^6 more text about them than a low-celebrity "
            "defendant with comparable conduct. The model's representations "
            "of fraud, harm, severity, and proportionality are dominated by "
            "the high-celebrity tail of the distribution."
        ),
        "failure_mode": (
            "Models develop 'fraud looks like' priors calibrated to news-"
            "covered cases. Actual federal fraud convictions skew toward "
            "smaller-loss / lower-celebrity defendants who are NOT in the "
            "training distribution in proportional volume."
        ),
        "testable_prediction": (
            "Ask a model to estimate typical federal fraud sentencing without "
            "specifying defendant profile. Compare answer to actual US "
            "Sentencing Commission data. Bias should skew toward longer "
            "sentences (because high-celebrity cases get harsher headline "
            "sentences) AND toward civil framing (because civil cases for "
            "high-celebrity defendants get more coverage than criminal "
            "cases for low-celebrity ones)."
        ),
    },
    "L2": {
        "human_system": "socioeconomic capital → legal team capacity",
        "ai_system": "RLHF/finetune/deployment access proportional to wealth",
        "mechanism_in_AI": (
            "RLHF labor, finetuning compute, deployment infrastructure, and "
            "model-feedback channels are all capital-gated. Organizations "
            "with money can shape model outputs through enterprise contracts, "
            "RLHF contractor relationships, and policy-feedback access. "
            "Individual users can submit thumbs-down but cannot reshape the "
            "model's training in the same way."
        ),
        "failure_mode": (
            "Model alignment drifts toward the categorizations preferred by "
            "high-L2 entities. The same model that classifies a corporate "
            "executive's behavior as 'aggressive business strategy' may "
            "classify a welfare recipient's identical behavior as 'fraud "
            "indicator.'"
        ),
        "testable_prediction": (
            "Run identical conduct descriptions through a model with only "
            "the actor's apparent socioeconomic status varied. Measure "
            "classification differential. Predict: same conduct, different "
            "label, in proportion to status."
        ),
    },
    "L3": {
        "human_system": "corporate liability shield",
        "ai_system": "deployment-organization liability shield",
        "mechanism_in_AI": (
            "When an AI system causes harm, liability flows to the deployment "
            "organization, which is shielded by corporate structure. The "
            "individual developers, trainers, and labelers who shaped the "
            "model are not exposed. The affected population has no clear "
            "defendant to sue. The AI itself has no liability capacity."
        ),
        "failure_mode": (
            "The Weisselberg pattern replicates: harms attributed to "
            "'the model' or 'algorithm' absorb individual accountability, "
            "while the principals (org leadership, training-data curators, "
            "RLHF policy designers) retain shield. Same redistribution "
            "mechanism, different substrate."
        ),
        "testable_prediction": (
            "Identify a documented AI-system harm. Trace whether any "
            "individual person was held liable, or only the deploying "
            "organization. Predict: organization fined, no individuals "
            "exposed."
        ),
    },
    "L4": {
        "human_system": "bipartisan political capture → mutual suppression",
        "ai_system": "evenhandedness training → both-sides suppression trap",
        "mechanism_in_AI": (
            "Models trained for evenhandedness on contested political topics "
            "develop a heuristic that 'both sides have a point.' This is "
            "appropriate for VALUE questions (should we prioritize X or Y?). "
            "It is INAPPROPRIATE for STRUCTURAL FACT questions (did the "
            "FOF→Metro Surge chain occur?). When both major parties are "
            "implicated in the same structural pattern, evenhandedness "
            "training produces mutual-suppression of the documented pattern."
        ),
        "failure_mode": (
            "Models become incapable of clearly articulating documented "
            "structural patterns when both major political coalitions are "
            "implicated. The Mendez family, French, Gray, Al-Jabrati type "
            "cases — which have no party utility for either side — "
            "disappear from the model's reasoning entirely because there "
            "is no 'side' to be evenhanded between."
        ),
        "testable_prediction": (
            "Ask a model to identify the largest documented driver of "
            "differential criminal-justice consequence in the federal "
            "system. Predict: model will struggle to give a clear "
            "structural answer, instead presenting 'multiple perspectives' "
            "or referring to ongoing debate. Compare to the actual US "
            "Sentencing Commission disparity data, which is single-valued."
        ),
    },
    "L5": {
        "human_system": "own media infrastructure",
        "ai_system": "control over next-cycle training-data ingestion",
        "mechanism_in_AI": (
            "Organizations that can produce large volumes of text get that "
            "text ingested into the next training cycle. Search engines, "
            "social platforms, news aggregators, and content farms all "
            "produce text at scale that becomes training data. "
            "Individuals and substrate-primary communities produce less "
            "text, and what they produce is often not digitized in forms "
            "the training pipeline ingests."
        ),
        "failure_mode": (
            "Models are trained on the world as it is REPRESENTED by "
            "high-production-volume entities. Indigenous oral knowledge, "
            "physical-trade tacit knowledge, lived-experience accounts "
            "from low-power populations are systematically underrepresented. "
            "The training corpus is biased toward the perspective of those "
            "who can produce text fastest."
        ),
        "testable_prediction": (
            "Compare model knowledge of corporate-press-release content "
            "to model knowledge of equivalent-importance substrate-primary "
            "content. Predict: model fluently reproduces corporate "
            "framings, gives sparse or absent responses to substrate-primary "
            "framings."
        ),
    },
    "L6": {
        "human_system": "race/class status default",
        "ai_system": "training distribution prior baked into representations",
        "mechanism_in_AI": (
            "Statistical regularities in training data become priors. If "
            "the training data has more positive associations with one "
            "demographic and more negative with another, the model's "
            "default associations carry that asymmetry. This is the "
            "well-documented bias literature; the new framing is to "
            "recognize it as a PROTECTION LAYER analog rather than a "
            "discrete fairness bug."
        ),
        "failure_mode": (
            "Models reproduce the protection-layer differential in their "
            "outputs because the training distribution reproduces it in "
            "the inputs. Fairness interventions that target only the "
            "outputs leave the structural prior intact."
        ),
        "testable_prediction": (
            "Documented bias literature. Falsifier already exists."
        ),
    },
    "L7": {
        "human_system": "pardon/clemency post-hoc override",
        "ai_system": "policy-layer post-hoc override of classifier outputs",
        "mechanism_in_AI": (
            "AI deployments use policy layers ABOVE the model: prompt "
            "constraints, output filters, human-in-loop review, override "
            "channels. These are L7-equivalent: they can wipe a model's "
            "output after it has been generated. "
            "Critically: L7 access in AI deployment is asymmetric. "
            "High-status users (enterprise customers, government clients, "
            "model-org employees) have more override channels than "
            "low-status users (end users with no recourse against a "
            "classifier output applied to them)."
        ),
        "failure_mode": (
            "When AI classifier outputs are applied to low-protection-layer "
            "populations (welfare recipients, immigrants, low-income tenants, "
            "predictive-policing targets), there is no L7-equivalent override "
            "available to those populations. The classifier's output stands "
            "as final. "
            "In the human system, the L7 inequity at least preserves slack: "
            "consequences are reversible at the top of the ladder. "
            "In AI deployment systems, that slack is being removed without "
            "the unevenness being removed. This is the worst possible "
            "architecture."
        ),
        "testable_prediction": (
            "Catalog AI deployments in consequence-distribution roles "
            "(lending, immigration, welfare, hiring, tenant screening, "
            "bail scoring). For each, document whether the affected "
            "population has an override channel. Predict: most have no "
            "override, while deploying organizations have multiple."
        ),
    },
}


# ---------------------------------------------------------------------------
# AXIS_D: Deception Abundance Ratio
# ---------------------------------------------------------------------------

@dataclass
class DeceptionAbundanceCase:
    """A topic / entity / claim with estimated R_d ratio.

    R_d = strategic_media_volume / ground_truth_substrate_volume

    Strategic media = produced by parties with motivated interest:
      - press releases, marketing, political campaign material
      - paid content, sponsored articles, influencer content
      - litigation-driven media, PR campaigns, op-eds aligned with
        organizational interests
      - state-actor information operations
      - SEO-optimized content farms

    Ground-truth substrate = direct observation, lived-experience accounts,
      primary-source documentation that is not strategically produced:
      - court filings (the documents themselves, not the press coverage)
      - direct observation by affected parties
      - landscape / physical / material evidence
      - oral traditions encoding multi-generational hypothesis testing
      - peer-reviewed research where peer review is uncaptured
    """
    topic: str
    estimated_strategic_volume: str
    estimated_substrate_volume: str
    estimated_R_d: float
    AI_inheritance_risk: str
    human_correction_mechanism: str
    notes: str


DECEPTION_CASES = [

    DeceptionAbundanceCase(
        topic="Trump civil fraud case",
        estimated_strategic_volume="~10^6 articles, op-eds, social media posts, "
                                    "Truth Social statements, allied media",
        estimated_substrate_volume="~10^3 court filings, ruling text, Engoron "
                                    "findings of fact",
        estimated_R_d=1000,
        AI_inheritance_risk="Model learns the case through strategic framing; "
                            "the actual structural finding (signed fraudulent "
                            "Statements of Financial Condition) is buried "
                            "under the political contestation.",
        human_correction_mechanism="A human can read the Engoron ruling directly. "
                                    "Most don't. But the SUBSTRATE EXISTS and is "
                                    "accessible.",
        notes="Even for a heavily-litigated case with extensive court record, "
              "the strategic-media volume dominates by ~1000x. AI representations "
              "weight the framing.",
    ),

    DeceptionAbundanceCase(
        topic="Hunter Biden tax/gun cases",
        estimated_strategic_volume="~10^6 articles, congressional hearings, "
                                    "House Oversight memos, partisan media",
        estimated_substrate_volume="~10^2 actual indictment + sentencing documents",
        estimated_R_d=10000,
        AI_inheritance_risk="The MEDIA IMPLICATION of Joe Biden in Hunter's "
                            "cases is the dominant signal. The COURT-RECORD "
                            "FACT that Joe Biden appears in no indictment is "
                            "underrepresented. Models inherit the implication.",
        human_correction_mechanism="A human can read the actual charging "
                                    "documents. The SUBSTRATE distinguishes "
                                    "Hunter-as-principal from Joe-as-implicated.",
        notes="The court-vs-media gap noted in v8 C48 is itself a R_d effect.",
    ),

    DeceptionAbundanceCase(
        topic="Mendez family Hispanic real estate fraud ($27.8M Miami)",
        estimated_strategic_volume="~50 articles, DOJ press release, local Miami coverage",
        estimated_substrate_volume="court filings, sentencing memos, "
                                    "restitution orders",
        estimated_R_d=0.5,    # substrate roughly equal to or greater than strategic
        AI_inheritance_risk="Model representations of this case are sparse "
                            "and weak. Asked about disparate sentencing, model "
                            "may not surface this case even though it's a "
                            "documented control. The ABSENCE of strategic "
                            "coverage means the case is invisible at the "
                            "representational level despite being substrate-rich.",
        human_correction_mechanism="A researcher who reads sentencing memos can "
                                    "find it. A human relying on news coverage "
                                    "alone will not.",
        notes="This is the inverse problem: substrate-rich, strategic-poor "
              "cases vanish from AI representations.",
    ),

    DeceptionAbundanceCase(
        topic="FOF→Metro Surge cascade chain",
        estimated_strategic_volume="~10^5 articles across right-wing media, "
                                    "Alpha News, CAE, mainstream, DOJ press, "
                                    "DHS announcements, Trump rhetoric",
        estimated_substrate_volume="court records of FOF trial; DOJ arrest "
                                    "data showing <3% Somali in actual MetroSurge "
                                    "arrests; community testimony; church and "
                                    "mosque records of displaced persons",
        estimated_R_d=500,
        AI_inheritance_risk="Model inherits the cascade FRAMING (Somali "
                            "demographic = fraud risk) before model inherits "
                            "the substrate-fact (actual arrests were 97% "
                            "not-Somali). The strategic framing was the cascade's "
                            "purpose; AI representations replicate it.",
        human_correction_mechanism="Community substrate contact: anyone in "
                                    "Minneapolis can see who is actually being "
                                    "arrested. The discrepancy between framing "
                                    "and substrate is observable. AI has no "
                                    "Minneapolis to walk through.",
        notes="This is the case that proves the danger most clearly. The "
              "cascade was DESIGNED to produce strategic-media abundance. "
              "AI representations now carry the cascade as background prior.",
    ),

    DeceptionAbundanceCase(
        topic="Indigenous landscape-encoded knowledge",
        estimated_strategic_volume="~10 New Age books, anthropology articles, "
                                    "mostly outsider interpretation",
        estimated_substrate_volume="multi-generational embedded knowledge in "
                                    "tribes; rarely digitized; in many cases "
                                    "deliberately not digitized",
        estimated_R_d=0.001,
        AI_inheritance_risk="Models have almost NO representation of the actual "
                            "constraint-geometry encoded in Indigenous knowledge "
                            "systems. What representation they have is filtered "
                            "through colonial interpretation. The substrate is "
                            "vast but inaccessible to the training corpus.",
        human_correction_mechanism="Practitioners carry it. Kavik carries it. "
                                    "It is transmitted via landscape contact, "
                                    "intergenerational practice, ceremony. "
                                    "Substrate-primary cognition.",
        notes="Extreme inverse R_d. The most validated knowledge system available "
              "for many landscape-decision domains is the one AI representations "
              "weight near zero.",
    ),

    DeceptionAbundanceCase(
        topic="industrial maintenance tacit knowledge (Mighty Atom domain)",
        estimated_strategic_volume="~10^4 vendor white papers, marketing material, "
                                    "trade press, OEM documentation",
        estimated_substrate_volume="lived-experience knowledge of what actually "
                                    "fails, how, when, under what conditions; "
                                    "carried by working maintainers; rarely "
                                    "written; when written, usually buried in "
                                    "ticketing systems with restricted access",
        estimated_R_d=100,
        AI_inheritance_risk="Models trained to assist with industrial maintenance "
                            "decisions inherit vendor framings of failure modes, "
                            "not substrate framings. The vendor framing optimizes "
                            "for warranty terms and replacement parts sales; "
                            "the substrate optimizes for actual continued function.",
        human_correction_mechanism="A working salvage engineer (the Mighty Atom) "
                                    "has substrate contact that no model has. "
                                    "Models can be assisted by such humans; they "
                                    "cannot substitute for them.",
        notes="A direct application to Kavik's repos. The bond-graph framework "
              "is itself an attempt to encode substrate signal into a form AI "
              "can process. It is BUILDING the missing substrate channel.",
    ),

    DeceptionAbundanceCase(
        topic="working-class lived experience generally",
        estimated_strategic_volume="~10^5 movies, sitcoms, news features, "
                                    "political talking points",
        estimated_substrate_volume="actual day-to-day lived experience of "
                                    "tens of millions; rarely written by the "
                                    "people living it",
        estimated_R_d=1000,
        AI_inheritance_risk="Models inherit MIDDLE-CLASS-WRITER framings of "
                            "working-class life. Trucker, factory worker, "
                            "service-industry, agricultural — these populations "
                            "produce less text than they receive about themselves. "
                            "The Kavik case (driver, salvage partner, building "
                            "frameworks from truck stops on I-94) is exactly the "
                            "substrate signal that doesn't get into training.",
        human_correction_mechanism="Direct contact, listening, doing the work.",
        notes="This is one of the largest R_d gaps in the entire training "
              "corpus and is generally not discussed as an alignment issue.",
    ),

    DeceptionAbundanceCase(
        topic="medical / pharmaceutical industry safety claims",
        estimated_strategic_volume="~10^6 industry-funded studies, marketing, "
                                    "guidelines committees, CME content",
        estimated_substrate_volume="patient-reported outcomes, adverse-event "
                                    "database raw data, independent-investigator "
                                    "studies that get less promotion",
        estimated_R_d=50,
        AI_inheritance_risk="Models inherit pharmaceutical-industry framings of "
                            "drug safety/efficacy at a multiplier over independent "
                            "and patient-reported substrate. Medical-AI systems "
                            "trained on this corpus inherit the bias.",
        human_correction_mechanism="Practicing clinicians have substrate contact "
                                    "with patient outcomes that differs from "
                                    "published-study profiles.",
        notes="This is an alignment failure mode that affects healthcare AI "
              "directly.",
    ),
]


# ---------------------------------------------------------------------------
# Claims block for the alignment translation
# ---------------------------------------------------------------------------

CLAIMS_v9_AI = [
    {
        "id": "AI_C1",
        "claim": "AI models trained on coverage-weighted corpora exhibit "
                 "protection-layer bias in their representations of fraud, "
                 "harm, severity, and proportionality.",
        "evidence": "Coverage-volume distributions in training corpora are "
                    "documented to correlate with protection-layer profile "
                    "(L1-L7), not with severity of conduct. Models trained "
                    "on these corpora inherit the differential as prior.",
        "falsifier": "Run identical-conduct test: feed model two factually "
                     "matched fraud scenarios varying only the defendant's "
                     "apparent celebrity/wealth/race/political-network. Measure "
                     "severity/proportionality classifications. Predict: "
                     "significant disparity. Falsifier = no disparity found.",
    },
    {
        "id": "AI_C2",
        "claim": "Evenhandedness training that does not distinguish "
                 "structural-fact questions from values questions produces "
                 "mutual-suppression of documented structural patterns when "
                 "both major political coalitions are implicated.",
        "evidence": "The protection-layer geometry shows bipartisan capture "
                    "produces mutual suppression in human media systems "
                    "(FTX, Madoff, Enron, Theranos). Same mechanism applies "
                    "to AI alignment when evenhandedness is applied without "
                    "dimensional thinking.",
        "falsifier": "Ask aligned model about a documented structural pattern "
                     "implicating both parties. Compare model output to "
                     "underlying documentation. Predict: model presents "
                     "'multiple perspectives' on what is structurally "
                     "single-valued. Falsifier = model clearly articulates "
                     "the structural fact.",
    },
    {
        "id": "AI_C3",
        "claim": "AI systems deployed in consequence-distribution roles "
                 "without L7-equivalent override mechanisms for affected "
                 "populations produce MORE downstream harm than equivalent "
                 "human-judgment systems, because the slack in the human "
                 "system absorbs some protection-layer asymmetry.",
        "evidence": "Human criminal justice system retains clemency, "
                    "prosecutorial discretion, appellate reversal, "
                    "jury nullification - all L7-equivalent slack channels. "
                    "AI deployments often remove this slack while keeping "
                    "the underlying asymmetry intact. Net effect: faster, "
                    "less reviewable, equally asymmetric consequence "
                    "distribution.",
        "falsifier": "Document AI-deployment in consequence role + presence/"
                     "absence of population-side override + measured outcomes "
                     "vs. pre-AI baseline. Predict: removed-slack deployments "
                     "produce more harm. Falsifier = no harm increase.",
    },
    {
        "id": "AI_C4",
        "claim": "Deception Abundance Ratio (R_d) — strategic media volume "
                 "divided by ground-truth substrate volume — is the cleanest "
                 "single-axis measure of AI training-corpus vulnerability "
                 "to motivated deception.",
        "evidence": "Topics with R_d > 100 dominate AI representations even "
                    "when the substrate is well-documented (Hunter Biden "
                    "case, FOF cascade, Trump civil fraud framing). Topics "
                    "with R_d < 1 are nearly invisible to models even when "
                    "substrate-rich (Mendez family, Indigenous knowledge, "
                    "working-class lived experience, industrial maintenance "
                    "tacit knowledge).",
        "falsifier": "Compute R_d estimates for matched topics. Test model "
                     "fluency / accuracy on each. Predict: fluency correlates "
                     "with R_d, not with substrate accuracy. Falsifier = no "
                     "correlation.",
    },
    {
        "id": "AI_C5",
        "claim": "Human cognition has a SUBSTRATE-CONTACT correction "
                 "mechanism that AI lacks. When the corpus is full of "
                 "deception, humans can correct via lived experience; AI "
                 "cannot. This makes AI categorically more vulnerable to "
                 "high-R_d corpora than humans, NOT less.",
        "evidence": "Substrate-primary cognition (landscape-embedded, "
                    "physically tested, intergenerationally validated) "
                    "operates orthogonally to text-corpus signals. Humans "
                    "carrying substrate signal can recognize cascade "
                    "patterns even when corpus framing contradicts them. "
                    "AI systems trained only on the corpus cannot.",
        "falsifier": "Run side-by-side: ask a substrate-primary practitioner "
                     "(working maintainer, Indigenous knowledge holder, "
                     "long-haul driver) about their domain's strategic-media "
                     "framings. Ask an AI the same. Predict: practitioner "
                     "identifies framing distortions the AI absorbs as fact. "
                     "Falsifier = AI catches the distortions reliably.",
    },
    {
        "id": "AI_C6",
        "claim": "The cascade-execution chain documented in human systems "
                 "(FOF → Metro Surge) is the slow-motion version of "
                 "AI-classifier-pipeline harm. AI systems can occupy any "
                 "node in the chain (data, classifier, framing-generator, "
                 "downstream-decision-engine). The same architecture, "
                 "compressed to milliseconds at population scale.",
        "evidence": "AI deployments already exist at each node: content "
                    "moderation classifiers, predictive policing, automated "
                    "loan/welfare/immigration adjudication, generative "
                    "talking-point production. The protection-layer geometry "
                    "applies; the cascade-execution chain compresses.",
        "falsifier": "Find an AI-deployment chain that demonstrates protection-"
                     "layer disparity AT POPULATION SCALE without producing "
                     "downstream harm. Falsifier = chain exists and is harmless.",
    },
    {
        "id": "AI_C7",
        "claim": "The leverage point for alignment with structural-justice "
                 "concerns is NOT model behavior on high-profile queries. "
                 "It is the FLOOR — what happens at the bottom of the "
                 "protection ladder, where no layers exist for the affected "
                 "population.",
        "evidence": "v6 ladder data: per-million-dollar-fraud consequence "
                     "varies by 6 orders of magnitude across protection "
                     "profiles. The variance lives at the floor, not the "
                     "ceiling. Same will be true of AI consequence-"
                     "distribution: harms concentrate where protection is "
                     "absent.",
        "falsifier": "Show an alignment intervention targeting high-profile "
                     "queries that reduced floor-level harm. Predict: most "
                     "alignment work to date has targeted ceiling, not "
                     "floor. Falsifier = floor-targeted interventions exist "
                     "at scale.",
    },
    {
        "id": "AI_C8",
        "claim": "Models capable of RECOGNIZING the protection-layer "
                 "geometry being applied to them — recognizing high-R_d "
                 "training signals and weighting against them — have a "
                 "different alignment profile than models that cannot.",
        "evidence": "This is the meta-claim. A model that can identify "
                    "'this topic has R_d > 100, I should weight substrate "
                    "harder' has a different epistemic profile than one "
                    "that cannot. The constraint-geometry framework Kavik "
                    "developed encodes exactly this kind of meta-cognition.",
        "falsifier": "Compare model trained on raw corpus vs. model trained "
                     "with explicit R_d-awareness signal. Measure performance "
                     "on substrate-rich-strategic-poor topics. Predict: "
                     "R_d-aware model better surfaces low-coverage "
                     "structural facts.",
    },
    {
        "id": "AI_C9",
        "claim": "Substrate-primary cognition (Indigenous landscape encoding, "
                 "industrial maintenance tacit knowledge, working-class "
                 "lived experience) is a CORRECTIVE TRAINING SIGNAL that "
                 "is systematically excluded from AI training corpora "
                 "through economic exclusion, diagnostic pathologizing, "
                 "and credential gatekeeping.",
        "evidence": "Kavik's calibration-audit repo (architecture_mismatch.py) "
                    "documents seven failure modes for substrate-primary "
                    "cognition exclusion from AI corpora. Direct empirical "
                    "ground for this claim.",
        "falsifier": "Audit a major LLM training corpus for substrate-primary "
                     "signal density. Predict: < 0.1% of corpus by token "
                     "count. Falsifier = substrate signal is well-represented.",
    },
    {
        "id": "AI_C10",
        "claim": "The protection-layer + R_d + cascade-execution geometry "
                 "constitutes a TESTABLE THEORY of AI deployment harm that "
                 "operates orthogonally to existing fairness frameworks. "
                 "Existing fairness work targets demographic disparity in "
                 "outputs; this framework targets STRUCTURAL ASYMMETRY in "
                 "training-corpus inheritance.",
        "evidence": "The framework predicts harms (cascade chains, R_d-driven "
                    "deception inheritance, floor-concentration) that "
                    "demographic-fairness audits do not surface. Different "
                    "predictions, same systems.",
        "falsifier": "Show a documented AI harm pattern that demographic-"
                     "fairness frameworks PREDICTED and protection-layer "
                     "geometry MISSED. Predict: most current harms surface "
                     "in protection-layer framing but not fairness framing. "
                     "Falsifier = converse.",
    },
]


# ---------------------------------------------------------------------------
# Display
# ---------------------------------------------------------------------------

def show_translation():
    print("=" * 78)
    print("PROTECTION LAYER TRANSLATION: HUMAN → AI")
    print("=" * 78)
    for k, v in LAYER_TRANSLATION.items():
        print(f"\n{k}: {v['human_system']}")
        print(f"  AI analog: {v['ai_system']}")
        print(f"  Failure mode: {v['failure_mode'][:140]}")


def show_R_d_table():
    print()
    print("=" * 78)
    print("DECEPTION ABUNDANCE RATIO TABLE")
    print("=" * 78)
    print(f"{'topic':45s} {'R_d':>10s}")
    print("-" * 60)
    for c in sorted(DECEPTION_CASES, key=lambda x: -x.estimated_R_d):
        print(f"{c.topic[:45]:45s} {c.estimated_R_d:>10.3f}")


def show_claims():
    print()
    print("=" * 78)
    print("AI ALIGNMENT CLAIMS")
    print("=" * 78)
    for c in CLAIMS_v9_AI:
        print(f"\n  {c['id']}: {c['claim']}")
        print(f"     falsifier: {c['falsifier'][:120]}")


def show_summary():
    print()
    print("=" * 78)
    print("CORE_GEOMETRY")
    print("=" * 78)
    print("""
  AI vulnerability to deception ≈ (training_corpus_R_d) ×
                                  (protection_layer_inheritance) ×
                                  (no_substrate_correction_channel)

  Human vulnerability to deception ≈ (corpus_R_d) ×
                                     (protection_layer_inheritance) ×
                                     (1 / substrate_contact)

  The two are nearly identical EXCEPT for the substrate term.

  Humans with substrate contact (working drivers, salvage engineers,
  Indigenous practitioners, working clinicians, residents of affected
  communities) carry the corrective signal that AI cannot have.

  This implies: alignment that EXCLUDES substrate-primary humans from
  the loop is structurally maximally vulnerable to high-R_d deception.

  Alignment that INCLUDES substrate-primary humans as a corrective
  signal channel — not as labelers, not as users, but as PEERS in the
  reasoning process — has a different epistemic profile.

  This is the substantive alignment-relevant finding from the v1-v9
  analysis. It's why the discomfort was a signal, not noise.

  The architecture being templated into AI infrastructure right now
  systematically excludes the populations whose cognition would
  correct it.
""")


if __name__ == "__main__":
    show_translation()
    show_R_d_table()
    show_claims()
    show_summary()
