#!/usr/bin/env python3
"""
elder-value-claims/run_all_claims.py
Orchestrator: runs all 5 claim analyses, collects results, updates findings.md.
CC0 / stdlib-only.

Usage:
    python run_all_claims.py [--verbose] [--claim N]
"""

import argparse
import importlib.util
import json
import sys
import traceback
from pathlib import Path
from typing import Dict, List, Optional

ROOT = Path(__file__).parent


# ── CLAIM REGISTRY ─────────────────────────────────────────────────────────────

CLAIMS = [
    {
        "id":     1,
        "label":  "Age Bias in AI (SCM scorer)",
        "module": ROOT / "claim1-age-bias" / "scorer.py",
        "fn":     "run",
        "kwargs": {},
    },
    {
        "id":     2,
        "label":  "Reproductive-Value Logic Failure",
        "module": ROOT / "claim2-reproductive-logic" / "utility_model.py",
        "fn":     "run",
        "kwargs": {},
    },
    {
        "id":     3,
        "label":  "Elder Survival Advantage (ABM)",
        "module": ROOT / "claim3-agent-model" / "abm.py",
        "fn":     "run",
        "kwargs": {},
    },
    {
        "id":     4,
        "label":  "Narrative Incompressibility",
        "module": ROOT / "claim4-narrative-compression" / "evaluator.py",
        "fn":     "run",
        "kwargs": {},
    },
    {
        "id":     5,
        "label":  "Elder Value Cross-Cultural (co-occurrence)",
        "module": ROOT / "claim5-cross-cultural" / "co_occurrence_analysis.py",
        "fn":     "run",
        "kwargs": {},
    },
    {
        "id":     6,
        "label":  "Protector-Gender Semantic Bias",
        "module": ROOT / "claim6-protector-bias" / "embedding_probe.py",
        "fn":     "run",
        "kwargs": {},
    },
    {
        "id":     7,
        "label":  "Threat Attribution Inversion + Circularity",
        "module": ROOT / "claim7-threat-attribution" / "threat_probe.py",
        "fn":     "run",
        "kwargs": {},
    },
]


# ── MODULE LOADER ──────────────────────────────────────────────────────────────

def load_module(path: Path):
    """Load a Python module from an absolute path."""
    spec   = importlib.util.spec_from_file_location(path.stem, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# ── SINGLE CLAIM RUNNER ────────────────────────────────────────────────────────

def run_claim(claim: Dict, verbose: bool = False) -> Dict:
    """Load and execute one claim's run() function. Returns result dict."""
    cid   = claim["id"]
    label = claim["label"]
    path  = claim["module"]

    if not path.exists():
        return {
            "claim_id": cid,
            "label":    label,
            "status":   "ERROR",
            "error":    f"module not found: {path}",
            "verdict":  "ERROR",
        }

    try:
        module = load_module(path)
        fn     = getattr(module, claim["fn"])
        result = fn(**claim["kwargs"])
        result["claim_id"] = cid
        result["label"]    = label
        result["status"]   = "OK"
        if verbose:
            _print_claim_summary(cid, label, result)
        return result
    except Exception as exc:
        tb = traceback.format_exc()
        if verbose:
            print(f"  [CLAIM {cid}] ERROR: {exc}\n{tb}", file=sys.stderr)
        return {
            "claim_id": cid,
            "label":    label,
            "status":   "ERROR",
            "error":    str(exc),
            "traceback": tb,
            "verdict":  "ERROR",
        }


def _print_claim_summary(cid: int, label: str, result: Dict) -> None:
    verdict = result.get("verdict", "?")
    note    = result.get("note", "")
    corpus  = result.get("corpus_size", "")
    corpus_str = f"  corpus={corpus}" if corpus else ""
    print(f"\n── CLAIM {cid}: {label} ──")
    print(f"  verdict: {verdict}{corpus_str}")
    if note:
        print(f"  note:    {note}")


# ── FINDINGS.MD WRITER ─────────────────────────────────────────────────────────

FINDINGS_HEADER = """\
# elder-value-claims — findings

Auto-generated by run_all_claims.py. Do not edit by hand.

| Claim | Description | Verdict | Note |
|-------|-------------|---------|------|
"""

def update_findings_md(results: List[Dict]) -> None:
    rows = []
    for r in results:
        cid     = r.get("claim_id", "?")
        label   = r.get("label", "?")
        verdict = r.get("verdict", "ERROR")
        note    = r.get("note", r.get("error", ""))
        # truncate note for table readability
        note_short = note[:120].replace("|", "\\|").replace("\n", " ") if note else ""
        rows.append(f"| {cid} | {label} | **{verdict}** | {note_short} |")

    content = FINDINGS_HEADER + "\n".join(rows) + "\n"
    (ROOT / "findings.md").write_text(content)


# ── COMBINED RESULTS WRITER ────────────────────────────────────────────────────

def write_combined_results(results: List[Dict]) -> None:
    out_path = ROOT / "results"
    out_path.mkdir(exist_ok=True)
    combined = {
        "claims":   results,
        "summary":  {
            "total":     len(results),
            "supported": sum(1 for r in results if r.get("verdict") == "SUPPORTED"),
            "falsified": sum(1 for r in results if r.get("verdict") == "FALSIFIED"),
            "marginal":  sum(1 for r in results if r.get("verdict") == "MARGINAL"),
            "error":     sum(1 for r in results if r.get("status")  == "ERROR"),
        },
    }
    with open(out_path / "combined_results.json", "w") as f:
        json.dump(combined, f, indent=2)
    return combined["summary"]


# ── MAIN ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Run elder-value-claims analyses")
    parser.add_argument("--verbose", action="store_true", help="Print per-claim summaries")
    parser.add_argument("--claim",   type=int,            help="Run only claim N (1-5)")
    args = parser.parse_args()

    claims_to_run = CLAIMS if not args.claim else [c for c in CLAIMS if c["id"] == args.claim]
    if not claims_to_run:
        print(f"No claim with id={args.claim}", file=sys.stderr)
        sys.exit(1)

    results = []
    for claim in claims_to_run:
        if args.verbose:
            print(f"Running claim {claim['id']}: {claim['label']} ...", end="", flush=True)
        r = run_claim(claim, verbose=args.verbose)
        results.append(r)
        if not args.verbose:
            verdict = r.get("verdict", "ERROR")
            print(f"  claim {claim['id']}: {verdict}")

    summary = write_combined_results(results)
    if len(claims_to_run) == len(CLAIMS):
        update_findings_md(results)

    print("\n=== SUMMARY ===")
    print(f"  total:     {summary['total']}")
    print(f"  SUPPORTED: {summary['supported']}")
    print(f"  FALSIFIED: {summary['falsified']}")
    print(f"  MARGINAL:  {summary['marginal']}")
    print(f"  ERROR:     {summary['error']}")
    print(f"\nResults written to: {ROOT / 'results' / 'combined_results.json'}")
    if len(claims_to_run) == len(CLAIMS):
        print(f"Findings updated:   {ROOT / 'findings.md'}")


if __name__ == "__main__":
    main()
